### ISSUE TITLE
Italic render

### ISSUE THREAD

**Issue by whistyun** [dayAndnight2018/MarkDownAvalonia#1]
Hi, can you test a bellow xaml to check render a text as italic.

I received [issue](https://github.com/whistyun/Markdown.Avalonia/issues/4#issuecomment-739446151) about italic from @dayAndnight2018.
I tried to reproduce it, however I can't.

I couldn't pinpoint the problem, but I think Avalonia itself may not be able to draw italics in your environment.
If TextBlock (not only CTextBlock and MarkdownScrollViewer) can't render as italic, I think it is better way to consult with Avalonia team.

Thanks to read off-topic issue.

```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"

        xmlns:ctxt="clr-namespace:ColorTextBlock.Avalonia;assembly=ColorTextBlock.Avalonia"
        xmlns:md="clr-namespace:Markdown.Avalonia;assembly=Markdown.Avalonia"

        mc:Ignorable="d" d:DesignWidth="200" d:DesignHeight="150"
        x:Class="ItalicTest.MainWindow"
        Title="ItalicTest">

  <StackPanel>

    <TextBlock FontFamily="Microsoft YaHei,Simsun,苹方-简,宋体-简" FontStyle="Italic">
      Hello, 你好
    </TextBlock>

    <ctxt:CTextBlock FontFamily="Microsoft YaHei,Simsun,苹方-简,宋体-简" FontStyle="Italic">
      <ctxt:CRun>
        Hello, 你好
      </ctxt:CRun>
    </ctxt:CTextBlock>

    <md:MarkdownScrollViewer>
      <md:MarkdownScrollViewer.Styles>
        <Style Selector="ctxt|CTextBlock">
          <Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简"/>
          <Setter Property="FontStyle" Value="Italic"/>
        </Style>
      </md:MarkdownScrollViewer.Styles>
      *Hello, 你好*
    </md:MarkdownScrollViewer>
  </StackPanel>

</Window>
```

[full project "ItalicTest.zip"](https://github.com/dayAndnight2018/MarkDownAvalonia/files/5648522/ItalicTest.zip)

**Comment by dayAndnight2018** [comment]
> Hi, can you test a bellow xaml to check render a text as italic.
> 
> I received [issue](https://github.com/whistyun/Markdown.Avalonia/issues/4#issuecomment-739446151) about italic from @dayAndnight2018.
> I tried to reproduce it, however I can't.
> 
> I couldn't pinpoint the problem, but I think Avalonia itself may not be able to draw italics in your environment.
> If TextBlock (not only CTextBlock and MarkdownScrollViewer) can't render as italic, I think it is better way to consult with Avalonia team.
> 
> Thanks to read off-topic issue.
> 
> ```
> <Window xmlns="https://github.com/avaloniaui"
>         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>         xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>         xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
> 
>         xmlns:ctxt="clr-namespace:ColorTextBlock.Avalonia;assembly=ColorTextBlock.Avalonia"
>         xmlns:md="clr-namespace:Markdown.Avalonia;assembly=Markdown.Avalonia"
> 
>         mc:Ignorable="d" d:DesignWidth="200" d:DesignHeight="150"
>         x:Class="ItalicTest.MainWindow"
>         Title="ItalicTest">
> 
>   <StackPanel>
> 
>     <TextBlock FontFamily="Microsoft YaHei,Simsun,苹方-简,宋体-简" FontStyle="Italic">
>       Hello, 你好
>     </TextBlock>
> 
>     <ctxt:CTextBlock FontFamily="Microsoft YaHei,Simsun,苹方-简,宋体-简" FontStyle="Italic">
>       <ctxt:CRun>
>         Hello, 你好
>       </ctxt:CRun>
>     </ctxt:CTextBlock>
> 
>     <md:MarkdownScrollViewer>
>       <md:MarkdownScrollViewer.Styles>
>         <Style Selector="ctxt|CTextBlock">
>           <Setter Property="FontFamily" Value="Microsoft YaHei,Simsun,苹方-简,宋体-简"/>
>           <Setter Property="FontStyle" Value="Italic"/>
>         </Style>
>       </md:MarkdownScrollViewer.Styles>
>       *Hello, 你好*
>     </md:MarkdownScrollViewer>
>   </StackPanel>
> 
> </Window>
> ```
> 
> [full project "ItalicTest.zip"](https://github.com/dayAndnight2018/MarkDownAvalonia/files/5648522/ItalicTest.zip)

Ok, I find it is the font family causes the effect. Maybe I need another font family config. Thanks, anyway.

**Comment by whistyun** [comment]
Thanks for testing!
